# Site
title:              "Benjamin Jay Young"
title_pro:          "Benjamin J. Young"
title_ath:          "Ben Young"
title_per:          "Ben"
bio:                "Polymath, Utilitarian, Skeptic, and Analyst."
location:           "Massillon, Ohio. United States"
description_pro:    "CTO, Senior Software Engineer, Affiliate Marketer, Day Trader, and Accredited Investor."
description_ath:    "UTR 5.0, NTRP 3.5, 140MPH+ Service, USTA Multi-title Winner, Gravel Cyclist, and Weight Lifter."
description:        "Father, Programmer, Athlete, Macro Economist, Biological Chemist, and Mad Scientist."
resume:             http://docs.google.com/document/d/e/2PACX-1vQdkok_7N2VJrJzUgS3cgvhDBoB03wJlrHWDkElIM7EQLyIXseeS0iHp2MjXFJFBRTgpx2dXYqT2bV9/pub
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
logo_alt:           'assets/img/logo_alt.png'
logo_ath:           'assets/img/logo_ath.png'
logo_ath:           'assets/img/logo_per.png'
background:         'assets/img/background.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                http://blaher.me

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed
# Comments
#disqus_shortname:   blaher

# Social
# if you don't have any of social below, comment the line.
google:
  analytics:       G-T9V6N8GD5W
#bing-verify:
linkedin:           blaher
github-url:         blaher
stackoverflow:      1007685/blaher
duolingo:           blaher
email:              blaher@pm.me

facebook:           blaher
instagram:          blaher09
#youtube:           blaher
spotify:            blaher
steam:              blaher
twitter:            imbenyoung

usta:               http://tennislink.usta.com/Leagues/reports/NTRP/SearchResults.aspx?Search=Name&SearchType=W&LastName=young&FirstName=benjamin
myutr:              663993
strava:             blaher
zwift:              726f3a91-b8dc-4e22-9dce-a947d5212c3f
fitbit:             2WJBW2

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: http://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
